name: Test-Els
on: push
jobs:
  fist_job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4.0.0
      - name: Node Version
        run: node --version        
      - name: Install node modules
        run: cd second-action && npm install && cd -
      - name: LS
        run: ls